#!/usr/bin/env node
import { build } from "esbuild";
import { readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(packageRoot, "src/client/browser-entry.tsx");
const browserGenerated = join(packageRoot, "src/generated/client-script.ts");
const stylesheetGenerated = join(packageRoot, "src/generated/stylesheet.ts");
const browserOutput = join(packageRoot, "target/app.js");
const stylesheetOutput = join(packageRoot, "target/app.css");
const check = process.argv.includes("--check");

await build({
  absWorkingDir: packageRoot,
  entryPoints: [entry],
  outfile: browserOutput,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "none",
});
const [bundle, stylesheet] = await Promise.all([
  readFile(browserOutput, "utf8"),
  readFile(stylesheetOutput, "utf8"),
]);
const browserSource = `/* Generated by scripts/build-browser.mjs. Do not edit by hand. */\nexport const CLIENT_SCRIPT = ${JSON.stringify(bundle)};\n`;
const stylesheetSource = `/* Generated by scripts/build-browser.mjs. Do not edit by hand. */\nexport const STYLESHEET = ${JSON.stringify(stylesheet)};\n`;
const [currentBrowser, currentStylesheet] = await Promise.all([
  readFile(browserGenerated, "utf8").catch(() => undefined),
  readFile(stylesheetGenerated, "utf8").catch(() => undefined),
]);
if (check) {
  await removeBuildOutputs();
  if (currentBrowser !== browserSource || currentStylesheet !== stylesheetSource) {
    throw new Error("Browser assets are stale; run pnpm build:browser");
  }
} else {
  await Promise.all([
    writeFile(browserGenerated, browserSource, "utf8"),
    writeFile(stylesheetGenerated, stylesheetSource, "utf8"),
  ]);
  await removeBuildOutputs();
}

async function removeBuildOutputs() {
  await Promise.all([
    rm(browserOutput, { force: true }),
    rm(stylesheetOutput, { force: true }),
  ]);
}
