export { createSurfaceClient } from "./client/create.js";
export { createInProcessSurfaceClientTransport } from "./client/transport.js";
export type {
  SurfaceClient,
  SurfaceClientCommandEnvelope,
  SurfaceClientDescriptorResult,
  SurfaceClientEventsResult,
  SurfaceClientRequestOptions,
  SurfaceClientRequiredRequestOptions,
} from "./client/contracts.js";
export type {
  SurfaceClientCommandRequest,
  SurfaceClientTransport,
  SurfaceClientTransportResult,
} from "./client-model.js";
export {
  SURFACE_TRANSPORT_OPERATIONS,
  createMessageSurfaceClientTransport,
  handleSurfaceTransportRequest,
} from "./transport.js";
export { createSurfaceHostEndpoint } from "./host.js";
export type {
  SurfaceHostEndpoint,
  SurfaceHostEndpointOptions,
} from "./host.js";
export type {
  MessageSurfaceClientTransportOptions,
  SurfaceCommandTransportRequest,
  SurfaceCommandTransportResponse,
  SurfaceDescriptorTransportRequest,
  SurfaceDescriptorTransportResponse,
  SurfaceEventsTransportRequest,
  SurfaceEventsTransportResponse,
  SurfaceTransportEnvelope,
  SurfaceTransportOperation,
  SurfaceTransportRequest,
  SurfaceTransportResponse,
  SurfaceTransportSender,
  SurfaceTransportSubscriber,
} from "./transport.js";
export type {
  ReadSurfaceEventsRequest,
  SurfaceEvent,
  SurfaceEventListener,
  SurfaceEventPage,
  SurfaceEventUnsubscribe,
} from "./model.js";
export type {
  ArchiveSessionRequest,
  AttachmentDraft,
  CancelSideQueryRequest,
  CancelTrackedConversationOperationRequest,
  CancelTrackedConversationOperationResult,
  CommandCatalogReadModel,
  CommandInvocationPreview,
  CommandPortEnvelope,
  CommandPortJsonResult,
  ConversationAssistantTextDeltaEvent,
  ConversationAttachmentsReadModel,
  ConversationOperationReadModel,
  DismissSideQueryRequest,
  DismissSideQueryResult,
  ExecuteCommandRequest,
  ExecuteCommandResult,
  ExecutionReferenceReadResult,
  HomeOptions,
  HomeReadModel,
  ModelEndpointListReadModel,
  ModelEndpointReadModel,
  OpenWorkbenchRequest,
  OpenWorkbenchResult,
  PendingGuidedFollowUpReadModel,
  PrepareConversationAttachmentRequest,
  PrepareConversationAttachmentResult,
  PreviewCommandInvocationRequest,
  QueueGuidedFollowUpRequest,
  QueueGuidedFollowUpResult,
  ReadConversationAttachmentsRequest,
  ReadExecutionReferenceRequest,
  ReadSessionTranscriptRequest,
  ReadSideQueryRequest,
  ReadSideQueryResult,
  ReadTrackedConversationOperationRequest,
  ReadTrackedConversationOperationResult,
  RegenerateTrackedConversationOperationRequest,
  RegenerateTrackedConversationOperationResult,
  RemoveConversationAttachmentRequest,
  RemoveConversationAttachmentResult,
  RenameSessionRequest,
  ResolveTrackedConversationApprovalRequest,
  ResolveTrackedConversationApprovalResult,
  ResolveTrackedConversationRecoveryRequest,
  ResolveTrackedConversationRecoveryResult,
  RestoreSessionRequest,
  SelectSessionRequest,
  SessionRow,
  SessionTranscriptReadResult,
  SetLayoutRequest,
  SetModeRequest,
  SettingsReadModel,
  ShellStatus,
  SideQueryReadModel,
  StartSideQueryRequest,
  StateSnapshot,
  SteerTrackedConversationOperationRequest,
  SteerTrackedConversationOperationResult,
  SubmitConversationOperationRequest,
  SubmitConversationOperationResult,
  UpdatePreferencesRequest,
} from "../model.js";
export type {
  ReadTeamConversationResult,
  TeamAvailability,
  TeamConversationListReadModel,
  TeamConversationPageReadModel,
  TeamConversationSummary,
  TeamDeliveryReadModel,
  TeamInvalidatedEvent,
  TeamMessageReadModel,
  TeamParticipantReadModel,
  TeamRoundReceipt,
  TeamRoundReadModel,
} from "../team/model.js";
export type {
  AddTeamParticipantRequest,
  CloseTeamConversationRequest,
  CreateTeamConversationRequest,
  ListTeamConversationsRequest,
  SetTeamCoordinatorRequest,
  SubmitTeamRoundRequest,
  UpdateTeamParticipantRequest,
} from "../team/port.js";
export type {
  DecidePlanProposalRequest,
  DismissPlanGenerationResult,
  ExecutePlanProposalRequest,
  ExecutePlanProposalResult,
  ListPlanProposalsRequest,
  PlanGenerationReadModel,
  PlanGenerationReference,
  PlanProposalListReadModel,
  ReadPlanGenerationResult,
  ReadPlanProposalRequest,
  ReadPlanProposalResult,
  RevisePlanProposalRequest,
  SelectPlanProposalRequest,
  StartPlanGenerationRequest,
} from "../plan/model.js";
export type {
  CancelGoalRequest,
  ChangeGoalStateRequest,
  GoalInvalidatedEvent,
  GoalReadModel,
  ReadGoalRequest,
  ReadGoalResult,
  StartGoalRequest,
} from "../goal/model.js";
