// Static Seatbelt runtime policies adapted from the provider research baseline.
// Request-specific rules are projected in profile.ts.

export const MACOS_SEATBELT_BASE_POLICY = [
  "(version 1)",
  "",
  "; inspired by Chrome's sandbox policy:",
  "; https://source.chromium.org/chromium/chromium/src/+/main:sandbox/policy/mac/common.sb;l=273-319;drc=7b3962fe2e5fc9e2ee58000dc8fbf3429d84d3bd",
  "; https://source.chromium.org/chromium/chromium/src/+/main:sandbox/policy/mac/renderer.sb;l=64;drc=7b3962fe2e5fc9e2ee58000dc8fbf3429d84d3bd",
  "",
  "; start with closed-by-default",
  "(deny default)",
  "",
  "; child processes inherit the policy of their parent",
  "(allow process-exec)",
  "(allow process-fork)",
  "(allow signal (target same-sandbox))",
  "",
  "; process-info",
  "(allow process-info* (target same-sandbox))",
  "",
  "(allow file-write-data",
  "  (require-all",
  "    (path \"/dev/null\")",
  "    (vnode-type CHARACTER-DEVICE)))",
  "",
  "; sysctls permitted.",
  "(allow sysctl-read",
  "  (sysctl-name \"hw.activecpu\")",
  "  (sysctl-name \"hw.busfrequency_compat\")",
  "  (sysctl-name \"hw.byteorder\")",
  "  (sysctl-name \"hw.cacheconfig\")",
  "  (sysctl-name \"hw.cachelinesize_compat\")",
  "  (sysctl-name \"hw.cpufamily\")",
  "  (sysctl-name \"hw.cpufrequency_compat\")",
  "  (sysctl-name \"hw.cputype\")",
  "  (sysctl-name \"hw.l1dcachesize_compat\")",
  "  (sysctl-name \"hw.l1icachesize_compat\")",
  "  (sysctl-name \"hw.l2cachesize_compat\")",
  "  (sysctl-name \"hw.l3cachesize_compat\")",
  "  (sysctl-name \"hw.logicalcpu_max\")",
  "  (sysctl-name \"hw.machine\")",
  "  (sysctl-name \"hw.model\")",
  "  (sysctl-name \"hw.memsize\")",
  "  (sysctl-name \"hw.ncpu\")",
  "  (sysctl-name \"hw.nperflevels\")",
  "  ; Chrome locks these CPU feature detection down a bit more tightly,",
  "  ; but mostly for fingerprinting concerns which isn't an issue for codex.",
  "  (sysctl-name-prefix \"hw.optional.arm.\")",
  "  (sysctl-name-prefix \"hw.optional.armv8_\")",
  "  (sysctl-name \"hw.packages\")",
  "  (sysctl-name \"hw.pagesize_compat\")",
  "  (sysctl-name \"hw.pagesize\")",
  "  (sysctl-name \"hw.physicalcpu\")",
  "  (sysctl-name \"hw.physicalcpu_max\")",
  "  (sysctl-name \"hw.logicalcpu\")",
  "  (sysctl-name \"hw.cpufrequency\")",
  "  (sysctl-name \"hw.tbfrequency_compat\")",
  "  (sysctl-name \"hw.vectorunit\")",
  "  (sysctl-name \"machdep.cpu.brand_string\")",
  "  (sysctl-name \"kern.argmax\")",
  "  (sysctl-name \"kern.hostname\")",
  "  (sysctl-name \"kern.maxfilesperproc\")",
  "  (sysctl-name \"kern.maxproc\")",
  "  (sysctl-name \"kern.osproductversion\")",
  "  (sysctl-name \"kern.osrelease\")",
  "  (sysctl-name \"kern.ostype\")",
  "  (sysctl-name \"kern.osvariant_status\")",
  "  (sysctl-name \"kern.osversion\")",
  "  (sysctl-name \"kern.secure_kernel\")",
  "  ; Python's ProcessPoolExecutor queries this through sysconf(_SC_SEM_NSEMS_MAX).",
  "  (sysctl-name \"kern.sysv.semmns\")",
  "  (sysctl-name \"kern.usrstack64\")",
  "  (sysctl-name \"kern.version\")",
  "  (sysctl-name \"sysctl.proc_cputype\")",
  "  (sysctl-name \"vm.loadavg\")",
  "  (sysctl-name-prefix \"hw.perflevel\")",
  "  (sysctl-name-prefix \"kern.proc.pgrp.\")",
  "  (sysctl-name-prefix \"kern.proc.pid.\")",
  "  (sysctl-name-prefix \"net.routetable.\")",
  ")",
  "",
  "; Allow Java to read some CPU info. This is misclassified as a \"write\" because",
  "; userspace passes a memory buffer to the sysctl, but conceptually it is a read.",
  "(allow sysctl-write",
  "  (sysctl-name \"kern.grade_cputype\"))",
  "",
  "; IOKit",
  "(allow iokit-open",
  "  (iokit-registry-entry-class \"RootDomainUserClient\")",
  ")",
  "",
  "; needed to look up user info, see https://crbug.com/792228",
  "(allow mach-lookup",
  "  (global-name \"com.apple.system.opendirectoryd.libinfo\")",
  ")",
  "",
  "; Needed for python multiprocessing on MacOS for the SemLock",
  "(allow ipc-posix-sem)",
  "",
  "; Needed for PyTorch/libomp on macOS to register OpenMP runtimes.",
  "(allow ipc-posix-shm-read-data",
  "  ipc-posix-shm-write-create",
  "  ipc-posix-shm-write-unlink",
  "  (ipc-posix-name-regex #\"^/__KMP_REGISTERED_LIB_[0-9]+$\"))",
  "",
  "(allow mach-lookup",
  "  (global-name \"com.apple.PowerManagement.control\")",
  ")",
  "",
  "; allow openpty()",
  "(allow pseudo-tty)",
  "(allow file-read* file-write* file-ioctl (literal \"/dev/ptmx\"))",
  "(allow file-read* file-write*",
  "  (require-all",
  "    (regex #\"^/dev/ttys[0-9]+\")",
  "    (extension \"com.apple.sandbox.pty\")))",
  "; PTYs created before entering seatbelt may lack the extension; allow ioctl",
  "; on those slave ttys so interactive shells detect a TTY and remain functional.",
  "(allow file-ioctl (regex #\"^/dev/ttys[0-9]+\"))"
].join("\n")

export const MACOS_SEATBELT_PLATFORM_DEFAULTS = [
  "; macOS platform defaults included when a split filesystem policy requests `:minimal`.",
  "",
  "; Read access to standard system paths",
  "(allow file-read* file-test-existence",
  "  (subpath \"/Library/Apple\")",
  "  (subpath \"/Library/Filesystems/NetFSPlugins\")",
  "  (subpath \"/Library/Preferences/Logging\")",
  "  (subpath \"/private/var/db/DarwinDirectory/local/recordStore.data\")",
  "  (subpath \"/private/var/db/timezone\")",
  "  (subpath \"/usr/lib\")",
  "  (subpath \"/usr/share\")",
  "  (subpath \"/Library/Preferences\")",
  "  (subpath \"/var/db\")",
  "  (subpath \"/private/var/db\"))",
  "",
  "; Map system frameworks + dylibs for loader.",
  "(allow file-map-executable",
  "  (subpath \"/Library/Apple/System/Library/Frameworks\")",
  "  (subpath \"/Library/Apple/System/Library/PrivateFrameworks\")",
  "  (subpath \"/Library/Apple/usr/lib\")",
  "  (subpath \"/System/Library/Extensions\")",
  "  (subpath \"/System/Library/Frameworks\")",
  "  (subpath \"/System/Library/PrivateFrameworks\")",
  "  (subpath \"/System/Library/SubFrameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/Frameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/PrivateFrameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/SubFrameworks\")",
  "  (subpath \"/usr/lib\"))",
  "",
  "; System Framework and AppKit resources",
  "(allow file-read* file-test-existence",
  "  (subpath \"/Library/Apple/System/Library/Frameworks\")",
  "  (subpath \"/Library/Apple/System/Library/PrivateFrameworks\")",
  "  (subpath \"/Library/Apple/usr/lib\")",
  "  (subpath \"/System/Library/Frameworks\")",
  "  (subpath \"/System/Library/PrivateFrameworks\")",
  "  (subpath \"/System/Library/SubFrameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/Frameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/PrivateFrameworks\")",
  "  (subpath \"/System/iOSSupport/System/Library/SubFrameworks\")",
  "  (subpath \"/usr/lib\"))",
  "",
  "; Allow guarded vnodes.",
  "(allow system-mac-syscall (mac-policy-name \"vnguard\"))",
  "",
  "; Determine whether a container is expected.",
  "(allow system-mac-syscall",
  "  (require-all",
  "    (mac-policy-name \"Sandbox\")",
  "    (mac-syscall-number 67)))",
  "",
  "; Allow resolution of standard system symlinks.",
  "(allow file-read-metadata file-test-existence",
  "  (literal \"/etc\")",
  "  (literal \"/tmp\")",
  "  (literal \"/var\")",
  "  (literal \"/private/etc/localtime\"))",
  "",
  "; Allow stat'ing of firmlink parent path components.",
  "(allow file-read-metadata file-test-existence",
  "  (path-ancestors \"/System/Volumes/Data/private\"))",
  "",
  "; Allow processes to get their current working directory.",
  "(allow file-read* file-test-existence",
  "  (literal \"/\"))",
  "",
  "; Allow FSIOC_CAS_BSDFLAGS as alternate chflags.",
  "(allow system-fsctl (fsctl-command FSIOC_CAS_BSDFLAGS))",
  "",
  "; Allow access to standard special files.",
  "(allow file-read* file-test-existence",
  "  (literal \"/dev/autofs_nowait\")",
  "  (literal \"/dev/random\")",
  "  (literal \"/dev/urandom\")",
  "  (literal \"/private/etc/master.passwd\")",
  "  (literal \"/private/etc/passwd\")",
  "  (literal \"/private/etc/protocols\")",
  "  (literal \"/private/etc/services\"))",
  "",
  "; Allow null/zero read/write.",
  "(allow file-read* file-test-existence file-write-data",
  "  (literal \"/dev/null\")",
  "  (literal \"/dev/zero\"))",
  "",
  "; Allow read/write access to the file descriptors.",
  "(allow file-read-data file-test-existence file-write-data",
  "  (subpath \"/dev/fd\"))",
  "",
  "; Provide access to debugger helpers.",
  "(allow file-read* file-test-existence file-write-data file-ioctl",
  "  (literal \"/dev/dtracehelper\"))",
  "",
  "; Allow reading standard config directories.",
  "(allow file-read* (subpath \"/etc\"))",
  "(allow file-read* (subpath \"/private/etc\"))",
  "",
  "(allow file-read* file-test-existence",
  "  (literal \"/System/Library/CoreServices\")",
  "  (literal \"/System/Library/CoreServices/.SystemVersionPlatform.plist\")",
  "  (literal \"/System/Library/CoreServices/SystemVersion.plist\"))",
  "",
  "; Some processes read /var metadata during startup.",
  "(allow file-read-metadata (subpath \"/var\"))",
  "(allow file-read-metadata (subpath \"/private/var\"))",
  "",
  "; IOKit access for root domain services.",
  "(allow iokit-open",
  "  (iokit-registry-entry-class \"RootDomainUserClient\"))",
  "",
  "; macOS Standard library queries opendirectoryd at startup",
  "(allow mach-lookup (global-name \"com.apple.system.opendirectoryd.libinfo\"))",
  "",
  "; Allow IPC to analytics, logging, trust, and other system agents.",
  "(allow mach-lookup",
  "  (global-name \"com.apple.analyticsd\")",
  "  (global-name \"com.apple.analyticsd.messagetracer\")",
  "  (global-name \"com.apple.appsleep\")",
  "  (global-name \"com.apple.bsd.dirhelper\")",
  "  (global-name \"com.apple.diagnosticd\")",
  "  (global-name \"com.apple.dt.automationmode.reader\")",
  "  (global-name \"com.apple.espd\")",
  "  (global-name \"com.apple.logd\")",
  "  (global-name \"com.apple.logd.events\")",
  "  (global-name \"com.apple.runningboard\")",
  "  (global-name \"com.apple.secinitd\")",
  "  (global-name \"com.apple.system.DirectoryService.libinfo_v1\")",
  "  (global-name \"com.apple.system.logger\")",
  "  (global-name \"com.apple.system.notification_center\")",
  "  (global-name \"com.apple.system.opendirectoryd.membership\")",
  "  (global-name \"com.apple.trustd\")",
  "  (global-name \"com.apple.trustd.agent\")",
  "  (global-name \"com.apple.xpc.activity.unmanaged\"))",
  "",
  "; Allow IPC to the syslog socket for logging.",
  "(allow network-outbound (literal \"/private/var/run/syslog\"))",
  "",
  "; macOS Notifications",
  "(allow ipc-posix-shm-read*",
  "  (ipc-posix-name \"apple.shm.notification_center\"))",
  "",
  "; Regulatory domain support.",
  "(allow file-read*",
  "  (literal \"/private/var/db/eligibilityd/eligibility.plist\"))",
  "",
  "; Audio and power management services.",
  "(allow mach-lookup (global-name \"com.apple.audio.audiohald\"))",
  "(allow mach-lookup (global-name \"com.apple.audio.AudioComponentRegistrar\"))",
  "(allow mach-lookup (global-name \"com.apple.PowerManagement.control\"))",
  "",
  "; Allow reading the minimum system runtime so exec works.",
  "(allow file-read-data (subpath \"/bin\"))",
  "(allow file-read-metadata (subpath \"/bin\"))",
  "(allow file-read-data (subpath \"/sbin\"))",
  "(allow file-read-metadata (subpath \"/sbin\"))",
  "(allow file-read-data (subpath \"/usr/bin\"))",
  "(allow file-read-metadata (subpath \"/usr/bin\"))",
  "(allow file-read-data (subpath \"/usr/sbin\"))",
  "(allow file-read-metadata (subpath \"/usr/sbin\"))",
  "(allow file-read-data (subpath \"/usr/libexec\"))",
  "(allow file-read-metadata (subpath \"/usr/libexec\"))",
  "",
  "(allow file-read* (subpath \"/Library/Preferences\"))",
  "(allow file-read* (subpath \"/System/Library/OpenSSL\"))",
  "(allow file-read* (subpath \"/opt/homebrew/Cellar\"))",
  "(allow file-map-executable (subpath \"/opt/homebrew/Cellar\"))",
  "(allow file-read* (subpath \"/opt/homebrew/opt\"))",
  "(allow file-map-executable (subpath \"/opt/homebrew/opt\"))",
  "(allow file-read* (subpath \"/opt/homebrew/lib\"))",
  "(allow file-read* (subpath \"/usr/local/Cellar\"))",
  "(allow file-map-executable (subpath \"/usr/local/Cellar\"))",
  "(allow file-read* (subpath \"/usr/local/opt\"))",
  "(allow file-map-executable (subpath \"/usr/local/opt\"))",
  "(allow file-read* (subpath \"/usr/local/lib\"))",
  "",
  "; Terminal basics and device handles.",
  "(allow file-read* (regex \"^/dev/fd/(0|1|2)$\"))",
  "(allow file-write* (regex \"^/dev/fd/(1|2)$\"))",
  "(allow file-read* file-write* (literal \"/dev/null\"))",
  "(allow file-read* file-write* (literal \"/dev/tty\"))",
  "(allow file-read-metadata (literal \"/dev\"))",
  "(allow file-read-metadata (regex \"^/dev/.*$\"))",
  "(allow file-read-metadata (literal \"/dev/stdin\"))",
  "(allow file-read-metadata (literal \"/dev/stdout\"))",
  "(allow file-read-metadata (literal \"/dev/stderr\"))",
  "(allow file-read-metadata (regex \"^/dev/tty[^/]*$\"))",
  "(allow file-read-metadata (regex \"^/dev/pty[^/]*$\"))",
  "(allow file-read* file-write* (regex \"^/dev/ttys[0-9]+$\"))",
  "(allow file-read* file-write* (literal \"/dev/ptmx\"))",
  "(allow file-ioctl (regex \"^/dev/ttys[0-9]+$\"))",
  "",
  "; Allow metadata traversal for firmlink parents.",
  "(allow file-read-metadata (literal \"/System/Volumes\") (vnode-type DIRECTORY))",
  "(allow file-read-metadata (literal \"/System/Volumes/Data\") (vnode-type DIRECTORY))",
  "(allow file-read-metadata (literal \"/System/Volumes/Data/Users\") (vnode-type DIRECTORY))",
  "",
  "; App sandbox extensions",
  "(allow file-read* (extension \"com.apple.app-sandbox.read\"))",
  "(allow file-read* file-write* (extension \"com.apple.app-sandbox.read-write\"))"
].join("\n")
